version: '3'

services:
# VS code in browser
# IDE for development running in docker and
# accessed in browser
  vscode:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile.vscode
    container_name: vscode
    image: vscode:latest
    ports:
      - "8080:8080"
    volumes:
      - vscode:/home/coder/.local/share/code-server
      - repo:/BilderSkriptRepo
    command: ["--auth", "none", "/BilderSkriptRepo"]
     
# hugin is an Open Source panorama stitcher and graphical user interface (GUI) 
# for Panorama tools. 
# It also provides a number of additional components and command line tools.
# 
# Hugin prepares image data taken with fisheye lenses. 
  hugin:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile.hugin
    image: hugin:latest
    volumes:
      - ipc:${APP_ROOT}/ipc
      - images:${APP_ROOT}/images
      - src:${APP_ROOT}/src
      - scripts:${APP_ROOT}/scripts
    command:
      /bilderskript/scripts/ipc_socket_server.sh hugin.sock /bilderskript/scripts/hugin/hugin_server_app.sh
    ipc: host
    stdin_open: true
    tty: true

# Ludwig is a toolbox that allows to train and test deep learning models
# without the need to write code. 
  ludwig:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile.ludwig
    image: ludwig:latest
    env_file:
      - .comet.env
    volumes:
      - ipc:${APP_ROOT}/ipc
      - images:${APP_ROOT}/images
      - ludwig:${APP_ROOT}/ludwig
      - log:${APP_ROOT}/log
      - scripts:${APP_ROOT}/scripts
    command:
      /bilderskript/scripts/ipc_socket_server.sh ludwig.sock /bilderskript/scripts/ludwig/ludwig_server_app.sh
    ipc: host
    stdin_open: true
    tty: true

# Builder contains all tooling for the BilderSkript application
# It defines and runs pipelines.
  builder:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile.builder
    image: builder:latest
    volumes:
      - repo:/BilderSkriptRepo
      - ipc:${APP_ROOT}/ipc
      - pipelines:${APP_ROOT}/pipelines
      - log:${APP_ROOT}/log
      - images:${APP_ROOT}/images
      - ludwig:${APP_ROOT}/ludwig
      - src:${APP_ROOT}/src
      - scripts:${APP_ROOT}/scripts
      - docs:${APP_ROOT}/docs
      - docs_site:${APP_ROOT}/docs_site
    ipc: host
    stdin_open: true
    tty: true

# hugin, same as above, but with vnc
# this is for running the Hugin GUI to configure the
# project (.pto) file.
  hugin-vnc:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile.hugin
    image: hugin:latest
    ports:
      - "5901:5901"
    volumes:
      - images:${APP_ROOT}/images
      - scripts:${APP_ROOT}/scripts
      - hugin-vnc:/hugin-vnc
    command:
#       /bin/bash
      /hugin-vnc/hugin.sh
    ipc: host
    stdin_open: true
    tty: true

#
# Volume definition
# Note the "ipc" volume for sharing UNIX sockets.
# 
volumes:
  repo:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}
  ipc:
  pipelines:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/pipelines
  vscode:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/vscode
  code-server:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/code-server
  log:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/log
  images:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/images
  ludwig:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/ludwig
  hugin-vnc:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/hugin-vnc
  src:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/src
  scripts:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/scripts
  docs:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/docs
  docs_site:
    driver_opts:
      type: none
      o: bind
      device: ${VOL_DIR}/docs_site
  