# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
datasets: datasets.csv
models: models.csv


dirs:
    # project's root dir
    project_dir: &project_dir
        "/bilderskript"
    # main tools installed by docker
    supplemental_dir: &supplemental_dir
        "/opt/builder"
    # scripts dir
    script_dir: &script_dir
        - *project_dir
        - "scripts"
    log_dir:
        - *project_dir
        - "log"

doc:
    # important variables
    docs_dir:
        - *project_dir 
        - "docs"
    docs_site: &docs_site
        - *project_dir 
        - "docs_site"
    hugo: 
        - *supplemental_dir
        - "hugo/hugo"
    plantuml_jar:
        - *supplemental_dir
        - "plantuml/plantuml.jar"

data_prep:
    datasets_idx:
        2
    out_dir:
        - *project_dir
        - "images/output"
    resize_width:
        500
    hugin_scripts: &hugin_scripts
        - *script_dir
        - "hugin"
    hugin_cmd:
        - *hugin_scripts
        - "hugin.sh"

ludwig:
    models_idx:
        1
    out_dir:
        - *project_dir
        - "ludwig/predict"
    ludwig_scripts: &ludwig_scripts
        - *script_dir
        - "ludwig"
    ludwig_cmd:
        - *ludwig_scripts
        - "ludwig.sh"
