import pandas as pd
from snakemake.utils import validate, min_version

##### set minimum snakemake version #####
min_version("5.1.2")

##### load config and sample sheets #####

configfile: "config.yaml"
# validate(config, schema="schemas/config.schema.yaml")

datasets = pd.read_table(config["datasets"], sep=";")
models = pd.read_table(config["models"], sep=";")
validate(datasets, schema="schemas/datasets.schema.yaml")


include: "util.py"


##### target rules #####


##### setup report #####

report: "report.rst"

#rule report:
#    input:
#        "report.rst"
#    output:
#        "report.html"
#    run:
#        from snakemake.utils import report
#        with open(input[0], 'r') as fh:
#            repdesc = fh.readlines()
#        report("".join(repdesc), output[0])

##### load rules #####

include: "doc.snakefile"
include: "data_prep.snakefile"
include: "ludwig.snakefile"

# include: "test.snakefile"
