import pandas as pd
from snakemake.utils import validate, min_version

##### set minimum snakemake version #####
min_version("5.1.2")

##### load config and sample sheets #####

configfile: "config.yaml"
# validate(config, schema="schemas/config.schema.yaml")

#samples = pd.read_table(config["datasets"], sep=";").set_index("sample", drop=False)
#validate(samples, schema="schemas/samples.schema.yaml")


##### target rules #####


##### setup report #####

# report: "report/workflow.rst"


##### load rules #####

include: "doc.snakefile"

# include: "data_prep.snakefile"
#include: "test.snakefile"
